-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.account
(
    pk_account serial NOT NULL,
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    roleid integer NOT NULL,
    status character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT account_pkey PRIMARY KEY (pk_account),
    CONSTRAINT account_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.address
(
    pk_address serial NOT NULL,
    customerid integer,
    provinceid integer,
    districtid integer,
    wardid integer,
    street_address text COLLATE pg_catalog."default",
    is_default integer,
    creation_date timestamp without time zone,
    edit_date timestamp without time zone,
    CONSTRAINT address_pkey PRIMARY KEY (pk_address)
);

CREATE TABLE IF NOT EXISTS public.brand
(
    pk_brand serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    note text COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT brand_pkey PRIMARY KEY (pk_brand)
);

CREATE TABLE IF NOT EXISTS public.cart_variation
(
    pk_cart_variation serial NOT NULL,
    cartitem_id integer,
    variation_id integer,
    CONSTRAINT cart_variation_pkey PRIMARY KEY (pk_cart_variation),
    CONSTRAINT uq_cartitem_id UNIQUE (cartitem_id)
);

CREATE TABLE IF NOT EXISTS public.cartitem
(
    pk_cartitem serial NOT NULL,
    customer_id integer,
    quantity integer,
    status character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT cartitem_pkey PRIMARY KEY (pk_cartitem)
);

CREATE TABLE IF NOT EXISTS public.category
(
    pk_category serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT category_pkey PRIMARY KEY (pk_category)
);

CREATE TABLE IF NOT EXISTS public.customer
(
    pk_customer serial NOT NULL,
    accountid integer,
    name character varying(255) COLLATE pg_catalog."default",
    address text COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    note text COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default",
    creation_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    edit_date timestamp with time zone,
    CONSTRAINT customer_pkey PRIMARY KEY (pk_customer),
    CONSTRAINT customer_accountid_key UNIQUE (accountid)
);

CREATE TABLE IF NOT EXISTS public.district
(
    pk_district serial NOT NULL,
    provinceid integer,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT district_pkey PRIMARY KEY (pk_district)
);

CREATE TABLE IF NOT EXISTS public.employee
(
    pk_employee serial NOT NULL,
    accountid integer,
    name character varying(255) COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'ACTIVE',
    creation_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    edit_date timestamp with time zone,
    CONSTRAINT employee_pkey PRIMARY KEY (pk_employee),
    CONSTRAINT employee_accountid_key UNIQUE (accountid)
);

CREATE TABLE IF NOT EXISTS public.images
(
    pk_images serial NOT NULL,
    productid integer,
    variationid integer,
    id_image character varying(255) COLLATE pg_catalog."default",
    set_default boolean DEFAULT false,
    CONSTRAINT images_pkey PRIMARY KEY (pk_images)
);

CREATE TABLE IF NOT EXISTS public.orderline
(
    pk_orderline serial NOT NULL,
    orderid integer NOT NULL,
    variationid integer,
    quantity integer,
    unit_price numeric(12, 2),
    price numeric(12, 2),
    status character varying(50) COLLATE pg_catalog."default",
    creation_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    edit_date timestamp with time zone,
    CONSTRAINT orderline_pkey PRIMARY KEY (pk_orderline)
);

CREATE TABLE IF NOT EXISTS public.paymentmethod
(
    pk_paymentmethod serial NOT NULL,
    type character varying(100) COLLATE pg_catalog."default",
    note text COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT paymentmethod_pkey PRIMARY KEY (pk_paymentmethod)
);

CREATE TABLE IF NOT EXISTS public.posorder
(
    pk_posorder serial NOT NULL,
    customerid integer,
    employeeid integer,
    creation_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    total_amount numeric(12, 2),
    total_payment numeric(12, 2),
    paymentmethodid integer,
    note text COLLATE pg_catalog."default",
    status character varying(50) COLLATE pg_catalog."default",
    order_date timestamp with time zone,
    payment_date timestamp with time zone,
    type_order character varying(50) COLLATE pg_catalog."default",
    addressid integer,
    CONSTRAINT posorder_pkey PRIMARY KEY (pk_posorder)
);

CREATE TABLE IF NOT EXISTS public.product
(
    pk_product serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    images text COLLATE pg_catalog."default",
    categoryid integer,
    brandid integer,
    CONSTRAINT product_pkey PRIMARY KEY (pk_product)
);

CREATE TABLE IF NOT EXISTS public.province
(
    pk_province serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT province_pkey PRIMARY KEY (pk_province),
    CONSTRAINT province_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.role
(
    pk_role serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT role_pkey PRIMARY KEY (pk_role)
);

CREATE TABLE IF NOT EXISTS public.variation
(
    pk_variation serial NOT NULL,
    productid integer NOT NULL,
    sku character varying(100) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    price numeric(12, 2),
    quantity integer DEFAULT 0,
    color character varying(100) COLLATE pg_catalog."default",
    material character varying(100) COLLATE pg_catalog."default",
    size character varying(100) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    sold integer DEFAULT 0,
    status character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT variation_pkey PRIMARY KEY (pk_variation),
    CONSTRAINT variation_sku_key UNIQUE (sku)
);

CREATE TABLE IF NOT EXISTS public.ward
(
    pk_ward serial NOT NULL,
    districtid integer,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT ward_pkey PRIMARY KEY (pk_ward)
);

ALTER TABLE IF EXISTS public.account
    ADD CONSTRAINT account_roleid_fkey FOREIGN KEY (roleid)
    REFERENCES public.role (pk_role) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.address
    ADD CONSTRAINT address_customerid_fkey FOREIGN KEY (customerid)
    REFERENCES public.customer (pk_customer) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.address
    ADD CONSTRAINT address_districtid_fkey FOREIGN KEY (districtid)
    REFERENCES public.district (pk_district) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.address
    ADD CONSTRAINT address_provinceid_fkey FOREIGN KEY (provinceid)
    REFERENCES public.province (pk_province) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.address
    ADD CONSTRAINT address_wardid_fkey FOREIGN KEY (wardid)
    REFERENCES public.ward (pk_ward) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cart_variation
    ADD CONSTRAINT cart_variation_cartitem_id_fkey FOREIGN KEY (cartitem_id)
    REFERENCES public.cartitem (pk_cartitem) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS uq_cartitem_id
    ON public.cart_variation(cartitem_id);


ALTER TABLE IF EXISTS public.cart_variation
    ADD CONSTRAINT cart_variation_variation_id_fkey FOREIGN KEY (variation_id)
    REFERENCES public.variation (pk_variation) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cartitem
    ADD CONSTRAINT cartitem_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customer (pk_customer) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.customer
    ADD CONSTRAINT customer_accountid_fkey FOREIGN KEY (accountid)
    REFERENCES public.account (pk_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS customer_accountid_key
    ON public.customer(accountid);


ALTER TABLE IF EXISTS public.district
    ADD CONSTRAINT district_provinceid_fkey FOREIGN KEY (provinceid)
    REFERENCES public.province (pk_province) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.employee
    ADD CONSTRAINT employee_accountid_fkey FOREIGN KEY (accountid)
    REFERENCES public.account (pk_account) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS employee_accountid_key
    ON public.employee(accountid);


ALTER TABLE IF EXISTS public.images
    ADD CONSTRAINT images_productid_fkey FOREIGN KEY (productid)
    REFERENCES public.product (pk_product) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.images
    ADD CONSTRAINT images_variationid_fkey FOREIGN KEY (variationid)
    REFERENCES public.variation (pk_variation) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.orderline
    ADD CONSTRAINT orderline_orderid_fkey FOREIGN KEY (orderid)
    REFERENCES public.posorder (pk_posorder) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_orderline_order_id
    ON public.orderline(orderid);


ALTER TABLE IF EXISTS public.orderline
    ADD CONSTRAINT orderline_variationid_fkey FOREIGN KEY (variationid)
    REFERENCES public.variation (pk_variation) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.posorder
    ADD CONSTRAINT posorder_addressid_fkey FOREIGN KEY (addressid)
    REFERENCES public.address (pk_address) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.posorder
    ADD CONSTRAINT posorder_customerid_fkey FOREIGN KEY (customerid)
    REFERENCES public.customer (pk_customer) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_posorder_customer_id
    ON public.posorder(customerid);


ALTER TABLE IF EXISTS public.posorder
    ADD CONSTRAINT posorder_employeeid_fkey FOREIGN KEY (employeeid)
    REFERENCES public.employee (pk_employee) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.posorder
    ADD CONSTRAINT posorder_paymentmethodid_fkey FOREIGN KEY (paymentmethodid)
    REFERENCES public.paymentmethod (pk_paymentmethod) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT product_brandid_fkey FOREIGN KEY (brandid)
    REFERENCES public.brand (pk_brand) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_product_brand_id
    ON public.product(brandid);


ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT product_categoryid_fkey FOREIGN KEY (categoryid)
    REFERENCES public.category (pk_category) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_product_category_id
    ON public.product(categoryid);


ALTER TABLE IF EXISTS public.variation
    ADD CONSTRAINT variation_productid_fkey FOREIGN KEY (productid)
    REFERENCES public.product (pk_product) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_variation_product_id
    ON public.variation(productid);


ALTER TABLE IF EXISTS public.ward
    ADD CONSTRAINT ward_districtid_fkey FOREIGN KEY (districtid)
    REFERENCES public.district (pk_district) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;</content>
<parameter name="filePath">d:\test\myproject\backend\database_schema.sql